const std = @import("std");

pub const resources_json =
    \\[
    \\{"uri":"report://status","name":"Live Status","description":"Current sync and connection status.","mimeType":"text/markdown"},
    \\{"uri":"report://chain-gaps","name":"Chain Gap Summary","description":"Summary of current profile-specific traceability gaps.","mimeType":"text/markdown"},
    \\{"uri":"report://rtm","name":"RTM Summary","description":"Summary of requirements traceability matrix coverage, including source-conflict counts.","mimeType":"text/markdown"},
    \\{"uri":"requirements://","name":"Requirements","description":"Requirement inventory with implementation, verification, and source-provenance summary. Exact requirement://<id> resources are available for all requirement nodes even though the catalog lists only a small sample.","mimeType":"text/markdown"},
    \\{"uri":"artifacts://","name":"Design Artifacts","description":"Design artifact inventory with source provenance and requirement-text conflict counts. Exact artifact://<artifact_id> resources are available for all artifact nodes even though the catalog lists only a small sample.","mimeType":"text/markdown"},
    \\{"uri":"user-needs://","name":"User Needs","description":"User need inventory with downstream requirement coverage. Exact user-need://<id> resources are available for all user needs even though the catalog lists only a small sample.","mimeType":"text/markdown"},
    \\{"uri":"tests://","name":"Tests","description":"Test and test group inventory with linked requirement coverage. Exact test://<id> and test-group://<id> resources are available for matching nodes even though the catalog lists only a small sample.","mimeType":"text/markdown"},
    \\{"uri":"risks://","name":"Risks","description":"Risk inventory with linked requirements and mitigation status. Exact risk://<id> resources are available for all risk nodes even though the catalog lists only a small sample.","mimeType":"text/markdown"},
    \\{"uri":"suspects://","name":"Suspects","description":"Nodes currently marked suspect and needing review. Exact suspect://<id> resources are available for all current suspect nodes even though the catalog lists only a small sample.","mimeType":"text/markdown"},
    \\{"uri":"serials://","name":"Known Product Serials","description":"Serial-bearing execution history grouped by product. Exact serials://<full_product_identifier> resources are available for all products with serial-bearing executions even though the catalog lists only a small sample.","mimeType":"text/markdown"},
    \\{"uri":"units://","name":"Known Units","description":"Known serial-numbered units with execution history. Exact unit://<serial_number>, serial://<serial_number>, and execution://<execution_id> resources are available for matching records even though the catalog lists only a small sample.","mimeType":"text/markdown"},
    \\{"uri":"code-files://","name":"Code Files","description":"Source and test files ranked by traceability linkage. Exact source-file://<path> and test-file://<path> resources are available for matching nodes even though the catalog lists only a small sample.","mimeType":"text/markdown"},
    \\{"uri":"mcp-tools://","name":"MCP Tools","description":"Resource-readable catalog of callable MCP tools exposed by this server.","mimeType":"text/markdown"},
    \\{"uri":"mcp-prompts://","name":"MCP Prompts","description":"Resource-readable catalog of MCP prompts exposed by this server.","mimeType":"text/markdown"},
    \\{"uri":"report://code-traceability","name":"Code Traceability Summary","description":"Summary of source and test file traceability.","mimeType":"text/markdown"},
    \\{"uri":"report://review","name":"Review Summary","description":"Summary of suspect items and requirement source conflicts requiring review.","mimeType":"text/markdown"}
    \\]
;

pub const prompts_json =
    \\[
    \\{"name":"trace_requirement","description":"Trace one requirement through source assertions, tests, risks, code, commits, and gaps.","arguments":[{"name":"id","description":"Requirement ID (e.g. REQ-001)","required":true}]},
    \\{"name":"trace_design_artifact","description":"Inspect one design artifact's extracted requirement assertions, conflicts, and null-text rows.","arguments":[{"name":"artifact_id","description":"Artifact ID (e.g. artifact://srs_docx/core)","required":true}]},
    \\{"name":"trace_user_need","description":"Trace one user need to its downstream requirements, verification, risks, and gaps.","arguments":[{"name":"id","description":"User Need ID (e.g. UN-001)","required":true}]},
    \\{"name":"trace_test","description":"Trace one test or test group to linked requirements, latest results, and open coverage concerns.","arguments":[{"name":"id","description":"Test ID or Test Group ID (e.g. TC-ATP-004 or TG-ECG)","required":true}]},
    \\{"name":"trace_risk","description":"Trace one risk to linked requirements, mitigations, verification evidence, and open exposure.","arguments":[{"name":"id","description":"Risk ID (e.g. RSK-010)","required":true}]},
    \\{"name":"trace_unit","description":"Summarize one serial-numbered unit's execution history, failures, and implicated tests.","arguments":[{"name":"serial_number","description":"Unit serial number (e.g. UNIT-1246)","required":true}]},
    \\{"name":"which_requirements_for_user_need","description":"Answer which requirements derive from one user need.","arguments":[{"name":"id","description":"User Need ID (e.g. UN-002)","required":true}]},
    \\{"name":"which_tests_for_requirement","description":"Summarize how one requirement is currently verified and what evidence is missing.","arguments":[{"name":"id","description":"Requirement ID (e.g. REQ-005 or SRS-015)","required":true}]},
    \\{"name":"product_execution_summary","description":"Summarize known serial-bearing execution history for one product.","arguments":[{"name":"full_product_identifier","description":"Product identifier (e.g. VS-200-REV-C)","required":true}]},
    \\{"name":"open_risk_summary","description":"Summarize risks that remain open, with residual severity and likely exposure.","arguments":[]},
    \\{"name":"part_blast_radius","description":"Summarize what breaks or needs review if a part disappears or goes EOL.","arguments":[{"name":"part","description":"Part number (e.g. BSS138LT1G)","required":true}]},
    \\{"name":"soup_component_review","description":"Review one SOUP component's anomaly documentation, version, license, and trace links.","arguments":[{"name":"full_product_identifier","description":"Product identifier (e.g. VS-200-REV-C)","required":true},{"name":"part","description":"Component name / part (e.g. mbedTLS)","required":true},{"name":"bom_name","description":"Optional SOUP BOM name","required":false},{"name":"revision","description":"Optional component version / revision","required":false}]},
    \\{"name":"requirement_change_review","description":"Review stale or impacted evidence after a requirement changed.","arguments":[{"name":"id","description":"Requirement ID (e.g. SRS-015)","required":true}]},
    \\{"name":"impact_of_change","description":"Analyze downstream impact from changing a traced node.","arguments":[{"name":"id","description":"Node ID (e.g. UN-001 or REQ-001)","required":true}]},
    \\{"name":"explain_gap","description":"Explain why RTMify raised a specific chain gap.","arguments":[{"name":"code","description":"Gap code (e.g. 1203)","required":true},{"name":"node_id","description":"Node ID tied to the gap","required":true}]},
    \\{"name":"audit_readiness_summary","description":"Summarize RTMify readiness for the selected profile.","arguments":[{"name":"profile","description":"Profile name (generic, medical, aerospace, automotive)","required":true}]},
    \\{"name":"repo_coverage_summary","description":"Summarize repo-backed implementation and test coverage.","arguments":[{"name":"repo","description":"Optional repo path filter","required":false}]},
    \\{"name":"design_history_summary","description":"Summarize design history for a requirement.","arguments":[{"name":"req_id","description":"Requirement ID (e.g. REQ-001)","required":true}]},
    \\{"name":"inspect_bom_item_traceability","description":"Review one BOM item's resolved and unresolved requirement/test links.","arguments":[{"name":"id","description":"Exact BOM item ID (e.g. bom-item://ASM-1000-REV-C/hardware/pcba/C0805-10UF@A)","required":false},{"name":"full_product_identifier","description":"Product identifier for composite BOM item lookup","required":false},{"name":"bom_type","description":"BOM type for composite lookup (hardware or software)","required":false},{"name":"bom_name","description":"BOM name for composite lookup","required":false},{"name":"part","description":"Part number for composite lookup","required":false},{"name":"revision","description":"Revision for composite lookup","required":false}]},
    \\{"name":"eol_impact","description":"Assess which Design BOMs and trace links are affected by an end-of-life part.","arguments":[{"name":"part","description":"Part number to assess","required":true}]},
    \\{"name":"bom_coverage","description":"Summarize BOM traceability coverage and unresolved refs for a product or Design BOM.","arguments":[{"name":"full_product_identifier","description":"Optional product identifier filter","required":false},{"name":"bom_name","description":"Optional BOM name filter","required":false}]},
    \\{"name":"component_substitute","description":"Review where a component is used and what requirement/test links it carries before substitution.","arguments":[{"name":"part","description":"Part number to evaluate","required":true}]},
    \\{"name":"soup_audit_prep","description":"Summarize SOUP inventory, anomaly documentation, and unresolved links for audit prep.","arguments":[{"name":"full_product_identifier","description":"Optional product identifier filter","required":false},{"name":"bom_name","description":"Optional SOUP BOM name filter","required":false}]},
    \\{"name":"soup_coverage","description":"Summarize SOUP traceability, safety class distribution, and license coverage.","arguments":[{"name":"full_product_identifier","description":"Optional product identifier filter","required":false},{"name":"bom_name","description":"Optional SOUP BOM name filter","required":false}]}
    \\]
;

pub const tools_json =
    \\[
    \\{"name":"list_workbooks","description":"List configured non-removed workbooks in this Live server.","inputSchema":{"type":"object","properties":{},"required":[]},"outputSchema":{"type":"object"}},
    \\{"name":"get_active_workbook","description":"Get the currently active workbook.","inputSchema":{"type":"object","properties":{},"required":[]},"outputSchema":{"type":"object"}},
    \\{"name":"switch_workbook","description":"Switch the active workbook by id or display name.","inputSchema":{"oneOf":[{"type":"object","properties":{"id":{"type":"string"}},"required":["id"]},{"type":"object","properties":{"display_name":{"type":"string"}},"required":["display_name"]}]},"outputSchema":{"type":"object"}},
    \\{"name":"list_design_artifacts","description":"List design artifacts and their requirement/conflict counts for the active workbook.","inputSchema":{"type":"object","properties":{},"required":[]},"outputSchema":{"type":"array"}},
    \\{"name":"get_design_artifact","description":"Get one design artifact with extracted requirement assertions, parse status, and source metadata.","inputSchema":{"type":"object","properties":{"artifact_id":{"type":"string"}},"required":["artifact_id"]},"outputSchema":{"type":"object"}},
    \\{"name":"get_rtm","description":"Get the Requirements Traceability Matrix. Optional limit/offset and suspect-only filtering.","inputSchema":{"type":"object","properties":{"limit":{"type":"integer"},"offset":{"type":"integer"},"suspect_only":{"type":"boolean"}},"required":[]},"outputSchema":{"type":"array"}},
    \\{"name":"get_gaps","description":"Get requirements with no test linked. Optional limit and offset.","inputSchema":{"type":"object","properties":{"limit":{"type":"integer"},"offset":{"type":"integer"}},"required":[]},"outputSchema":{"type":"array"}},
    \\{"name":"get_suspects","description":"Get all suspect nodes. Optional limit and offset.","inputSchema":{"type":"object","properties":{"limit":{"type":"integer"},"offset":{"type":"integer"}},"required":[]},"outputSchema":{"type":"array"}},
    \\{"name":"get_nodes","description":"Get graph nodes, optionally filtered by type. Supports limit and offset.","inputSchema":{"type":"object","properties":{"type":{"type":"string"},"limit":{"type":"integer"},"offset":{"type":"integer"}},"required":[]},"outputSchema":{"type":"array"}},
    \\{"name":"get_node","description":"Get a single node by ID. Set include_edges or include_properties to false to omit those sections from the result.","inputSchema":{"type":"object","properties":{"id":{"type":"string"},"include_edges":{"type":"boolean","default":true},"include_properties":{"type":"boolean","default":true}},"required":["id"]},"outputSchema":{"type":"object"}},
    \\{"name":"search","description":"Full-text search across node IDs and properties. Supports limit.","inputSchema":{"type":"object","properties":{"q":{"type":"string"},"limit":{"type":"integer"}},"required":["q"]},"outputSchema":{"type":"array"}},
    \\{"name":"get_user_needs","description":"Get User Need nodes. Optional limit and offset.","inputSchema":{"type":"object","properties":{"limit":{"type":"integer"},"offset":{"type":"integer"}},"required":[]},"outputSchema":{"type":"array"}},
    \\{"name":"get_tests","description":"Get Test nodes with linked requirements. Optional limit and offset.","inputSchema":{"type":"object","properties":{"limit":{"type":"integer"},"offset":{"type":"integer"}},"required":[]},"outputSchema":{"type":"array"}},
    \\{"name":"get_risks","description":"Get the risk register. Optional limit and offset.","inputSchema":{"type":"object","properties":{"limit":{"type":"integer"},"offset":{"type":"integer"}},"required":[]},"outputSchema":{"type":"array"}},
    \\{"name":"get_impact","description":"Get impact analysis for a node.","inputSchema":{"type":"object","properties":{"id":{"type":"string"}},"required":["id"]},"outputSchema":{"type":"array"}},
    \\{"name":"get_schema","description":"Get the graph schema: node types, edge labels, and meanings.","inputSchema":{"type":"object","properties":{},"required":[]},"outputSchema":{"type":"object"}},
    \\{"name":"get_status","description":"Get sync state, connection, and license status.","inputSchema":{"type":"object","properties":{},"required":[]},"outputSchema":{"type":"object"}},
    \\{"name":"clear_suspect","description":"Mark a suspect node as reviewed.","inputSchema":{"type":"object","properties":{"id":{"type":"string"}},"required":["id"]},"outputSchema":{"type":"object"}},
    \\{"name":"code_traceability","description":"Source and test files with annotation counts. Supports repo and limit.","inputSchema":{"type":"object","properties":{"repo":{"type":"string"},"limit":{"type":"integer"}},"required":[]},"outputSchema":{"type":"object"}},
    \\{"name":"unimplemented_requirements","description":"Requirements with no IMPLEMENTED_IN edge.","inputSchema":{"type":"object","properties":{"limit":{"type":"integer"},"offset":{"type":"integer"}},"required":[]},"outputSchema":{"type":"array"}},
    \\{"name":"untested_source_files","description":"Source files with no VERIFIED_BY_CODE edge.","inputSchema":{"type":"object","properties":{"limit":{"type":"integer"},"offset":{"type":"integer"}},"required":[]},"outputSchema":{"type":"array"}},
    \\{"name":"file_annotations","description":"Code annotations found in a specific source file.","inputSchema":{"type":"object","properties":{"file_path":{"type":"string"},"limit":{"type":"integer"}},"required":["file_path"]},"outputSchema":{"type":"array"}},
    \\{"name":"blame_for_requirement","description":"Code annotations with blame data linked to a requirement.","inputSchema":{"type":"object","properties":{"req_id":{"type":"string"},"limit":{"type":"integer"}},"required":["req_id"]},"outputSchema":{"type":"array"}},
    \\{"name":"commit_history","description":"Commits linked to a requirement via COMMITTED_IN edges. Supports limit.","inputSchema":{"type":"object","properties":{"req_id":{"type":"string"},"limit":{"type":"integer"}},"required":["req_id"]},"outputSchema":{"type":"array"}},
    \\{"name":"design_history","description":"Full upstream/downstream chain for a requirement.","inputSchema":{"type":"object","properties":{"req_id":{"type":"string"}},"required":["req_id"]},"outputSchema":{"type":"object"}},
    \\{"name":"get_test_results","description":"Get ingested test results for a test case, newest first.","inputSchema":{"type":"object","properties":{"test_case_ref":{"type":"string"}},"required":["test_case_ref"]},"outputSchema":{"type":"array"}},
    \\{"name":"get_execution","description":"Get a stored test execution by execution_id.","inputSchema":{"type":"object","properties":{"execution_id":{"type":"string"}},"required":["execution_id"]},"outputSchema":{"type":"object"}},
    \\{"name":"get_verification_status","description":"Get verification rollup and latest results for a requirement.","inputSchema":{"type":"object","properties":{"requirement_ref":{"type":"string"}},"required":["requirement_ref"]},"outputSchema":{"type":"object"}},
    \\{"name":"get_dangling_results","description":"Get ingested test results that do not resolve to a known Test node.","inputSchema":{"type":"object","properties":{},"required":[]},"outputSchema":{"type":"array"}},
    \\{"name":"get_unit_history","description":"Get test execution history for a serial number, newest first.","inputSchema":{"type":"object","properties":{"serial_number":{"type":"string"}},"required":["serial_number"]},"outputSchema":{"type":"array"}},
    \\{"name":"get_bom","description":"Get BOM trees for a product, optionally filtered by bom_type or bom_name. Obsolete products are hidden by default; set include_obsolete=true to include them. BOM item properties may include declared requirement_ids and test_ids.","inputSchema":{"type":"object","properties":{"full_product_identifier":{"type":"string"},"bom_type":{"type":"string","enum":["hardware","software"]},"bom_name":{"type":"string"},"include_obsolete":{"type":"boolean","default":false}},"required":["full_product_identifier"]},"outputSchema":{"type":"object"}},
    \\{"name":"get_bom_item","description":"Get a single BOM item, its parent chains, resolved requirement/test links, and unresolved declared refs.","inputSchema":{"oneOf":[{"type":"object","properties":{"id":{"type":"string"}},"required":["id"]},{"type":"object","properties":{"full_product_identifier":{"type":"string"},"bom_type":{"type":"string","enum":["hardware","software"]},"bom_name":{"type":"string"},"part":{"type":"string"},"revision":{"type":"string"}},"required":["full_product_identifier","bom_type","bom_name","part","revision"]}]},"outputSchema":{"type":"object","properties":{"node":{"type":"object"},"parent_chains":{"type":"array"},"linked_requirements":{"type":"array"},"linked_tests":{"type":"array"},"unresolved_requirement_ids":{"type":"array","items":{"type":"string"}},"unresolved_test_ids":{"type":"array","items":{"type":"string"}}},"required":["node","parent_chains","linked_requirements","linked_tests","unresolved_requirement_ids","unresolved_test_ids"]}},
    \\{"name":"list_design_boms","description":"List Design BOMs with product, lifecycle status, type, source format, ingest timestamp, and item count. Obsolete products are hidden by default; set include_obsolete=true to include them.","inputSchema":{"type":"object","properties":{"full_product_identifier":{"type":"string"},"bom_name":{"type":"string"},"include_obsolete":{"type":"boolean","default":false}},"required":[]},"outputSchema":{"type":"object"}},
    \\{"name":"find_part_usage","description":"Find which Design BOMs and parent assemblies use a specific part number. Obsolete products are hidden by default; set include_obsolete=true to include them.","inputSchema":{"type":"object","properties":{"part":{"type":"string"},"include_obsolete":{"type":"boolean","default":false}},"required":["part"]},"outputSchema":{"type":"object"}},
    \\{"name":"bom_gaps","description":"Find BOM items with unresolved requirement/test refs or declared trace refs that do not resolve. Superseded, EOL, and Obsolete products are excluded by default; set include_inactive=true to include them.","inputSchema":{"type":"object","properties":{"full_product_identifier":{"type":"string"},"bom_name":{"type":"string"},"include_inactive":{"type":"boolean","default":false}},"required":[]},"outputSchema":{"type":"object"}},
    \\{"name":"bom_impact_analysis","description":"Return Design BOM item coverage and linked requirement/test nodes for one product BOM. Obsolete products are hidden by default; set include_obsolete=true to include them.","inputSchema":{"type":"object","properties":{"full_product_identifier":{"type":"string"},"bom_name":{"type":"string"},"include_obsolete":{"type":"boolean","default":false}},"required":["full_product_identifier","bom_name"]},"outputSchema":{"type":"object"}},
    \\{"name":"list_software_boms","description":"List software Design BOMs and SOUP registers. Obsolete products are hidden by default; set include_obsolete=true to include them.","inputSchema":{"type":"object","properties":{"full_product_identifier":{"type":"string"},"bom_name":{"type":"string"},"include_obsolete":{"type":"boolean","default":false}},"required":[]},"outputSchema":{"type":"object"}},
    \\{"name":"get_soup_components","description":"Get flattened SOUP component rows, statuses, and unresolved refs for one product/BOM. Obsolete products are hidden by default; set include_obsolete=true to include them.","inputSchema":{"type":"object","properties":{"full_product_identifier":{"type":"string"},"bom_name":{"type":"string"},"include_obsolete":{"type":"boolean","default":false}},"required":["full_product_identifier"]},"outputSchema":{"type":"object"}},
    \\{"name":"soup_by_safety_class","description":"Get SOUP components for one product filtered by safety_class. Obsolete products are hidden by default; set include_obsolete=true to include them.","inputSchema":{"type":"object","properties":{"full_product_identifier":{"type":"string"},"safety_class":{"type":"string"},"include_obsolete":{"type":"boolean","default":false}},"required":["full_product_identifier","safety_class"]},"outputSchema":{"type":"object"}},
    \\{"name":"soup_by_license","description":"Get SOUP/software components filtered by product and/or license string. Obsolete products are hidden by default; set include_obsolete=true to include them.","inputSchema":{"type":"object","properties":{"full_product_identifier":{"type":"string"},"license":{"type":"string"},"include_obsolete":{"type":"boolean","default":false}},"required":[]},"outputSchema":{"type":"object"}},
    \\{"name":"get_product_serials","description":"Get serial-bearing test executions scoped to a product.","inputSchema":{"type":"object","properties":{"full_product_identifier":{"type":"string"}},"required":["full_product_identifier"]},"outputSchema":{"type":"array"}},
    \\{"name":"get_components_by_supplier","description":"Get BOM components linked through CONTAINS edges with a matching supplier.","inputSchema":{"type":"object","properties":{"supplier":{"type":"string"}},"required":["supplier"]},"outputSchema":{"type":"array"}},
    \\{"name":"get_software_components","description":"Get software BOM components, optionally filtered by purl prefix or license.","inputSchema":{"type":"object","properties":{"purl_prefix":{"type":"string"},"license":{"type":"string"}},"required":[]},"outputSchema":{"type":"array"}},
    \\{"name":"chain_gaps","description":"Traceability chain gaps for the active or requested industry profile. Supports severity, profile, limit, and offset.","inputSchema":{"type":"object","properties":{"profile":{"type":"string"},"severity":{"type":"string"},"limit":{"type":"integer"},"offset":{"type":"integer"}},"required":[]},"outputSchema":{"type":"array"}},
    \\{"name":"implementation_changes_since","description":"Find requirements or user needs whose implementation files changed since an ISO timestamp. This uses file/commit history, not explicit COMMITTED_IN message references. Supports repo, limit, and offset.","inputSchema":{"type":"object","properties":{"since":{"type":"string"},"node_type":{"type":"string","enum":["Requirement","UserNeed"]},"repo":{"type":"string"},"limit":{"type":"integer"},"offset":{"type":"integer"}},"required":["since","node_type"]},"outputSchema":{"type":"array"}},
    \\{"name":"requirement_trace","description":"Concise markdown trace summary for a requirement.","inputSchema":{"type":"object","properties":{"id":{"type":"string"}},"required":["id"]}},
    \\{"name":"gap_explanation","description":"Concise markdown explanation for a specific chain gap.","inputSchema":{"type":"object","properties":{"code":{"type":"integer"},"node_id":{"type":"string"}},"required":["code","node_id"]}},
    \\{"name":"impact_summary","description":"Concise markdown impact summary for a node.","inputSchema":{"type":"object","properties":{"id":{"type":"string"}},"required":["id"]}},
    \\{"name":"status_summary","description":"Concise markdown summary of Live status.","inputSchema":{"type":"object","properties":{},"required":[]}},
    \\{"name":"review_summary","description":"Concise markdown summary of suspects and open chain gaps.","inputSchema":{"type":"object","properties":{},"required":[]}}
    \\]
;

pub const initialize_result =
    \\{"protocolVersion":"2024-11-05","capabilities":{"tools":{},"resources":{},"prompts":{}},"serverInfo":{"name":"rtmify-live","version":"1.0"}}
;

pub const json_rpc_headers = [_]std.http.Header{
    .{ .name = "Content-Type", .value = "application/json" },
    .{ .name = "Connection", .value = "close" },
};
